parser: '@typescript-eslint/parser'

plugins:
  - jsdoc
  - import
  - '@stylistic'

ignorePatterns:
  - node_modules/
  - build/

extends:
  - raven
  - '@kesills/airbnb-typescript/base'
  - plugin:jsdoc/recommended
  - plugin:@stylistic/disable-legacy

globals:
  chrome: true
  document: true
  window: true

env:
  browser: true

parserOptions:
  project: ./tsconfig.json
  sourceType: module

rules:
  '@stylistic/indent': [error, tab]
  '@stylistic/semi': [error, always]
  '@stylistic/no-trailing-spaces': 1
  # @typescript-eslint/no-throw-literal has been deprecated
  # in favor of @typescript-eslint/only-throw-error
  '@typescript-eslint/no-throw-literal': 0
  '@typescript-eslint/only-throw-error': error
  '@stylistic/comma-dangle': [error, never]
  '@stylistic/space-before-function-paren': [error, never]
  '@typescript-eslint/naming-convention':
  - error
  - selector: variable
    format: [camelCase]
    filter:
      regex: '^(_isESmodule)$'
      match: false

  jsdoc/require-jsdoc:
    - error
    - require:
        ArrowFunctionExpression: true
        ClassExpression: true
        FunctionDeclaration: true
        MethodDefinition: true
  jsdoc/require-param-type: 0
  jsdoc/require-returns-type: 0
  jsdoc/no-undefined-types: 0

  # Box2D follows a PascalCase naming convention
  new-cap: [error, { capIsNewExceptionPattern: "(b2dbody|Box2D)\\.." }]

  # for loops and game coordinate variables
  id-length: [warn, { exceptions: [
    i, j, k,
    x, y, 
    r, g, b
    ] }]

  no-trailing-spaces: [error, { ignoreComments: true }]
  import/extensions: [error, ignorePackages]
  multiline-comment-style: [error, separate-lines]
  linebreak-style: 0
  sort-keys: 0
  no-labels: 0
  no-undef: 0
